blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	#url(r'^$', views.post_list, name='post_list'),
	url(r'^$', views.PostListView.as_view(), name='post_list'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
		r'(?P<post>[-\w]+)/$',
		views.post_detail,
		name='post_detail'),
	url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
]

rrgsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# need to add pytz module. then change the datetime settings.py to true again
class PublishedManager(models.Manager):
	def get_queryset(self):
		return super (PublishedManager, self).get_queryset().filter(status='published')
	
		
class Post(models.Model):
	 STATUS_CHOICES = (
	 	('draft', 'Draft'),
	 	('published', 'Published'), #take note of this comma, it means "list" or "tuple"
	 	)
	 title = models.CharField(max_length=250)
	 slug = models.SlugField(max_length=250, unique_for_date = 'publish')
	 author = models.ForeignKey(User, related_name='blog_posts')
	 body = models.TextField()
	 publish = models.DateTimeField(default=timezone.now)
	 created = models.DateTimeField(auto_now_add=True)
	 updated = models.DateTimeField(auto_now=True)
	 status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

	 objects = models.Manager()
	 published = PublishedManager()

	 def get_absolute_url(self):
	 	return reverse('blog:post_detail',
	 		args=[self.publish.year,self.publish.strftime('%m'),self.publish.strftime('%d'),self.slug])

	 class Meta:
	 	ordering = ('-publish', ) #defines meta data, the order is priority for publish then descend

	 def __str__(self): #do not forget the space between def and the underscores, returns terrible error
	 	return self.title

class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments')
	name = models.CharField(max_length=80)
	email= models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)
		
	def __str__(self):
			return 'Comment by {} on {}'.format(self.name, self.post)


				
			

rrgmedia/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
	"""docstring for EmailPostForm"""
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)
	
class CommentForm(forms.ModelForm):
	"""docstring for ClassName"""
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')

		
		

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail

def post_list(request):
	posts = Post.published.all()
	paginator = Paginator(object_list, 3) # 3 posts per page
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		#if page is not an integer deliver the first page
		posts =paginator.page(1)
	except EmptyPage:
		#if page is out of range deliver the last page results
		posts = paginator.page(paginator.num_pages)
	return  render(request, 'blog/post/list.html',{'page': page,'posts': posts})

def post_detail(request, year, month, day, post):
	post = get_object_or_404(Post, slug=post,\
		status='published',publish__year=year,\
		publish__month=month,publish__day=day)

	comments = post.comments.filter(active=True) # this queryset lists active comments for this blogpost/article
	if request.method=='POST':
		#A comment was posted
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			#create Comment Object but do not save to database
			new_comment = comment_form.save(commit=False)

			#assign the current post to the comment
			new_comment.post = post

			#Save the comment to the database
			new_comment.save()
	else:
		comment_form = CommentForm()

	return render(request,'blog/post/detail.html',{'post', post, 'comments', comments,'comment_form', comment_form})

class PostListView(ListView):
	"""docstring for PostListView"""
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 3
	template_name = 'blog/post/list.html'

#we want to share posts via email so

def post_share(request, post_id): 
#retrieve post by ID
	post = get_object_or_404(Post, id=post_id, status='published')# making sure we retrive posts by id and published status
	sent = False

	if request.method == 'POST':
		#form was submitted
		form = EmailPostForm(request.POST) #this is POST to send data not the articles
		if  form.is_valid():
			cd = form.cleaned_data  #Form passed validation, returns an empty form fields and stores their values
			post_url = request.build_absolute_url(post.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'. format(post.title, post_url, cd['name'], cd['comments'])
			send_mail(subject, message, 'lionelnyawose@gmail.com', [cd['to']])
			sent = True

	else:
		form = EmailPostForm()  # defined in forms.py

		return render(request, 'blog/post/share.html',{'post', post, 'form', form, 'sent', sent})

	


		



	

# Create your views here.

rrgmedia/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} {% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{%  static "css/blog.css" %}">
</head>
<body>

<!-- 	<nav>
		<ul>
			<li><a href=""> Home</a></li>
			<li><a href=""></a>Space Center</li>
			<li><a href=""></a>Fire</li>
		</ul>
	</nav>
 -->
 <div id="sidebar">
<H2>Zulunauts</H2>
<p>Count your blessings, light a cigarette and blow towards heaven. Thank your luck and content yourself to always being second!</p>
</div>
<!-- always start with the side bar before the main content so its easier to style -->

<div id="content">
{% block content %}
{% endblock %}
</div>

<footer>
	<p>Copyright&copy Zulunaut project</p>

</footer>

<script type="text/javascript" href="{% static "js/blog.js" %}"></script>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<H1>{{ post.title }}</H1>
<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>	
{{ post.body|linebreaks }}
<p>
	<!-- here we build the URL dynamically -->
	<a href="{% url "blog:post_share" post.id %}">Share this post</a>
</p>
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Zulunauts{% endblock %}

{% block content %}
	<H1>{{ post.title }}</H1>
	{% for post in posts %}
	<h2 class="big_head">
	 <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
	</h2>
	<p class="date">
		Published {{ post.publish }} by {{ post.author }}
	</p>	
	{{ post.body|truncatewords:30|linebreaks }}
{% endfor %}
{% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share Post{% endblock %}

{% block content %}
	{% if sent %}
	<h1>Email sucessfully sent</h1>
	<p>
		"{{ post.title }}" was succesfully sent to {{ cd.to }}
	</p>
	{% else %}
	<h1>Share "{{ post.title }}" by email</h1>
	<form action="." method="post">
		{{  form.as_p }}
		{% csrf_token %}
		<input type="submit" value="Send email">
	</form>
{% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
		<a href="?page={{ page.previous_page_number }}">Previous</a>
		{% endif %}
		<span class="current">
			Page {{ page.number }} of {{ page.paginator.num_pages }}.
		</span>
		{% if page.has_next %}
		<a href="?page={{ page.next_page_number }}">Next</a>
		{% endif %}
	</span>
</div>